#!/usr/bin/env node
// Converts dist/index.html → gzipped C header for PROGMEM embedding
import { readFileSync, writeFileSync } from "fs";
import { gzipSync } from "zlib";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const distPath = resolve(__dirname, "../dist/index.html");
const outPath = resolve(__dirname, "../../src/web/dashboard_gz.h");

const html = readFileSync(distPath);
const gz = gzipSync(html, { level: 9 });

const lines = [];
const perLine = 16;
for (let i = 0; i < gz.length; i += perLine) {
  const chunk = Array.from(gz.slice(i, i + perLine))
    .map((b) => `0x${b.toString(16).padStart(2, "0")}`)
    .join(", ");
  lines.push(`    ${chunk}`);
}

const header = `#pragma once
// AUTO-GENERATED by web/scripts/generate-header.mjs — do not edit
#include <pgmspace.h>

static const uint8_t DASHBOARD_HTML_GZ[] PROGMEM = {
${lines.join(",\n")}
};

static const size_t DASHBOARD_HTML_GZ_LEN = ${gz.length};
`;

writeFileSync(outPath, header);

const htmlKB = (html.length / 1024).toFixed(1);
const gzKB = (gz.length / 1024).toFixed(1);
console.log(
  `[generate-header] ${htmlKB}KB HTML → ${gzKB}KB gzip → src/web/dashboard_gz.h`,
);
